### ISSUE TITLE
MONGODB_URI is now MONGOLAB_URI

### ISSUE THREAD

**Issue by ismaelc** [hirako2000/hackathon-board#2]
I ran into some DB connection errors and traced it down to this environment variable. Maybe add MONGOLAB_URI to the secrets file

**Comment by hirako2000** [comment]
this variable is optional since secrets.js defines the db URI, perhaps adjust it to point to your mongodb location:

`db: process.env.MONGODB || process.env.MONGOLAB_URI || 'mongodb://localhost:27017/test'`

Can you provide some error log?

**Comment by ismaelc** [comment]
Error is like this (see below).  I'll close this one for now

2016-05-10T01:08:54.746031+00:00 app[web.1]: Express server listening on port 25430 in production mode
2016-05-10T01:08:54.755041+00:00 app[web.1]: MongoDB Connection Error. Please make sure that MongoDB is running.
2016-05-10T01:08:54.759468+00:00 app[web.1]: 
2016-05-10T01:08:54.759492+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:236
2016-05-10T01:08:54.759493+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-05-10T01:08:54.759494+00:00 app[web.1]:                                       ^
2016-05-10T01:08:54.759498+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2016-05-10T01:08:54.759499+00:00 app[web.1]:     at Object.exports._errnoException (util.js:893:11)
2016-05-10T01:08:54.759499+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:916:20)
2016-05-10T01:08:54.759500+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1075:14)
2016-05-10T01:08:54.770382+00:00 app[web.1]:

**Comment by hirako2000** [comment]
Mongodb needs to be running indeed.

**Comment by ismaelc** [comment]
It thinks Mongo is not running because MongoLab is using a different environment variable

**Comment by hirako2000** [comment]
From what I see [here](https://devcenter.heroku.com/articles/mongolab), the env variable should be set from Heroku
I'm fine pulling a change to add the extra variable.
